### ISSUE TITLE
isPost()

### ISSUE THREAD

**Issue by AdamSmid** [geniv/nette-comgate#1]
Nice nette repo! :) 

I would just correct action method in your ReadMe:

```php
public function actionStatus()
    {
          $request = $this->context->getByType(Request::class);
          if ($request->isPost()) {
```
to
```php
public function actionStatus()
    {
        $this->getHttpResponse()->setContentType("application/javascript");
        $request = $this->getHttpRequest();
        if ($request->getMethod() == "POST") {
..
...
....
```
I would suggest to set ContentType, because Comgate need clear response with code and message. With enabled debug mode (and Tracy). It will add Tracy bar at the end of the page. Also isPost() is deprecated since 2.3.0 and removed in 2.4.0 I guess.

But overall - Very good job!

**Comment by geniv** [comment]
Hi, thanks! :) 
yes you right. I will fix this code.

**Comment by geniv** [comment]
fixed, thank a lot off!
